name: Clean up old workflow runs
on:
  schedule:
    - cron: '4 0 * * *' # Daily at midnight
  workflow_dispatch: # Manual trigger

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: iamazeem/delete-workflow-runs-action@v1
        with:
          keep: 1
